// generated by _tools/gen_commands.go
package main

func init() {
	commands["checkout"] = command{
		action:      doCheckout,
		name:        "checkout",
		usage:       "Checkout a branch for a pull request",
		description: "checkout [-f TEMPLATE] PULL_REQUEST_NUMBER\n\nChecks out a branch corresponding to given pull request number.  The branch\nname is based on the template, which defaults to\n'#{{.Number}}-{{.Head.Repo.Owner.Login}}/{{.Head.Ref}}'.",
	}
	commands["list"] = command{
		action:      doList,
		name:        "list",
		usage:       "List pull requests",
		description: "list\n\nLists pull requests for current project.",
	}
	commands["merge"] = command{
		action:      doMerge,
		name:        "merge",
		usage:       "Merge a branch of a pull request",
		description: "merge BRANCH\n\nInvokes 'git merge' for the branch created with 'hub-pr checkout' with a\ndefault commit message including Pull Request number and title, similar to the\nGitHub Merge Button.",
	}
	commands["browse"] = command{
		action:      doBrowse,
		name:        "browse",
		usage:       "Open pull request page with browser",
		description: "browse\n\nOpens a web browser for the URL of Pull Request corresponding to current branch.",
	}
}
